#!/bin/bash

if [ -f $HOME/.cargo/env ]; then
  source "$HOME/.cargo/env"
fi

export EDITOR="nvim"
# export DISPLAY="localhost:10.0"
export DIFFTOOL=delta

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
# Load pyenv-virtualenv automatically by adding
# the following to ~/.bashrc:

eval "$(pyenv virtualenv-init -)"

# chezmoi
export PATH="$HOME/bin/:$PATH"

# nvim
export PATH="/opt/nvim-linux64/bin:$PATH"

# fzf
export PATH="$HOME/.fzf/bin:$PATH"

# bat
export PATH="$HOME/.local/bin:$PATH"

if command -v thefuck &>/dev/null; then
  # integration
  eval $(thefuck --alias)
  # You can use whatever you want as an alias, like for Mondays:
  eval $(thefuck --alias fk)
fi

# ---- Zoxide (better cd) ----
eval "$(zoxide init zsh)"
alias cd="z"

# ---- Eza (better ls) -----
alias ls="eza --icons=always"
