#!/bin/bash

# chezmoi
export PATH="$HOME/bin/:$PATH"

# nvim
# export PATH="/opt/nvim-linux64/bin:$PATH"
export PATH="/opt/nvim-linux-x86_64/bin:$PATH"

# fzf
export PATH="$HOME/.fzf/bin:$PATH"

# bat
export PATH="$HOME/.local/bin:$PATH"

if [ -f $HOME/.cargo/env ]; then
  source "$HOME/.cargo/env"
fi

if [ -f $HOME/.duckdb ]; then
  export PATH='/home/ybyan/.duckdb/cli/latest':$PATH
fi
