#!/bin/bash

if [ -f $HOME/.cargo/env ]; then
  source "$HOME/.cargo/env"
fi

export EDITOR="nvim"
export DISPLAY="localhost:10.0"

# chezmoi
export PATH=$PATH:$HOME/bin/

# nvim
export PATH="$PATH:/opt/nvim-linux64/bin"
