#!/bin/bash
# Bootstrap the Nix backend for mise, so system packages mise can't provide
# natively (unzip, xclip, and future OS deps) are installed from nixpkgs via the
# `nix:` backend (jbadeau/mise-nix) -- with no scattered `sudo apt`.
#
#   nix present            -> ensure flakes + mise-nix plugin, declare packages
#   nix absent + can sudo  -> install Nix once (Determinate installer), then above
#   nix absent + no sudo   -> report the packages we can't install, then skip
#
# Add future system dependencies to NIX_PACKAGES below. This is a run_onchange_
# script: editing it (e.g. the package list) re-runs it on the next `chezmoi apply`.

export PATH="$HOME/.local/bin:$PATH"   # ensure mise is reachable

# ---- packages to install from nixpkgs (edit me) ----
NIX_PACKAGES=(unzip xclip)

FRAGMENT="$HOME/.config/mise/conf.d/nix-system.toml"

nix_available() { command -v nix >/dev/null 2>&1; }

can_escalate() {
  [ "$(id -u)" -eq 0 ] && return 0
  command -v sudo >/dev/null 2>&1 || return 1
  if sudo -n true 2>/dev/null; then return 0; fi   # passwordless sudo
  if [ -t 0 ] && [ -t 1 ]; then                    # interactive: allow one prompt
    sudo -v && return 0
  fi
  return 1
}

install_nix() {
  echo "[nix] installing Nix via the Determinate Systems installer..."
  ( set -o pipefail
    curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix \
      | sh -s -- install --no-confirm ) || return 1
  # make nix reachable in this shell for any follow-up
  local p=/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  [ -e "$p" ] && . "$p"
  nix_available
}

enable_flakes() {
  local conf="$HOME/.config/nix/nix.conf"
  mkdir -p "$(dirname "$conf")"
  if ! grep -qs 'experimental-features' "$conf" 2>/dev/null; then
    echo "experimental-features = nix-command flakes" >>"$conf"
    echo "[nix] enabled flakes in $conf"
  fi
}

ensure_backend_plugin() {
  if ! mise plugins ls 2>/dev/null | grep -qiw nix; then
    echo "[nix] registering mise-nix backend plugin..."
    mise plugin install nix https://github.com/jbadeau/mise-nix.git
  fi
}

write_fragment() {
  mkdir -p "$(dirname "$FRAGMENT")"
  {
    echo "# Auto-generated by run_onchange_after_mise-nix-setup.sh -- do not hand-edit."
    echo "# System packages from nixpkgs, installed via the mise nix: backend."
    echo "[tools]"
    for p in "${NIX_PACKAGES[@]}"; do
      printf '"nix:%s" = "latest"\n' "$p"
    done
  } >"$FRAGMENT"
  echo "[nix] declared ${#NIX_PACKAGES[@]} package(s) in ${FRAGMENT/#$HOME/\~}."
  echo "[nix] run 'mise install' to install: ${NIX_PACKAGES[*]}"
}

skip() {
  echo "[nix] Nix is not installed and no sudo access is available."
  echo "[nix] These system packages will be SKIPPED (install manually, or re-run"
  echo "[nix] on a host with sudo to bootstrap Nix): ${NIX_PACKAGES[*]}"
  rm -f "$FRAGMENT"   # keep 'mise install' clean where nix is unavailable
}

if ! command -v mise >/dev/null 2>&1; then
  echo "[nix] mise not found on PATH; skipping nix backend setup." >&2
  exit 0
fi

if ! nix_available; then
  if can_escalate; then
    if ! install_nix; then
      echo "[nix] Nix installation failed." >&2
      skip
      exit 0
    fi
  else
    skip
    exit 0
  fi
fi

enable_flakes
ensure_backend_plugin
write_fragment
